--- 
abstract: HTTP Cookie parser in C
author: 
  - Agent Zhang <agentzh@yahoo.cn>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Cookie-XS
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.1
version: 0.09
